packages:
  - 'backend'
  - 'frontend/*'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  vue-demi: true
